# Generated by Django 3.0.7 on 2020-08-03 17:15

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('dashboard', '0002_delete_appoint'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Appointment',
            new_name='Appointment1',
        ),
    ]
