# Generated by Django 3.0.7 on 2020-08-03 17:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_appoint'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Appoint',
            new_name='Appointment',
        ),
    ]
