# Generated by Django 3.1 on 2020-08-21 12:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_profile_full_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='amount',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='margin',
        ),
    ]
