# Generated by Django 3.0.7 on 2020-08-03 18:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_auto_20200803_1930'),
    ]

    operations = [
        migrations.RenameField(
            model_name='appointment',
            old_name='timestamp',
            new_name='created',
        ),
        migrations.RemoveField(
            model_name='appointment',
            name='time',
        ),
    ]
