# Generated by Django 3.1 on 2020-10-23 08:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_auto_20201005_1457'),
    ]

    operations = [
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('illness', models.CharField(blank=True, max_length=1000)),
                ('Doctor', models.CharField(blank=True, max_length=100)),
                ('Description', models.CharField(blank=True, max_length=10000)),
                ('patient', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='patientnote', to='core.profile')),
            ],
        ),
    ]
