# Generated by Django 3.1 on 2020-11-01 10:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_auto_20201031_1956'),
    ]

    operations = [
        migrations.RenameField(
            model_name='note',
            old_name='Description',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='note',
            old_name='Doctor',
            new_name='doctor',
        ),
    ]
