# Generated by Django 3.1 on 2020-11-02 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_auto_20201101_1100'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='patientfullname',
            field=models.CharField(blank=True, max_length=1000),
        ),
        migrations.AlterField(
            model_name='note',
            name='doctor',
            field=models.CharField(blank=True, max_length=1000),
        ),
    ]
