# Generated by Django 3.1 on 2020-12-03 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_auto_20201203_1021'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='dob',
            field=models.DateField(max_length=10, null=True),
        ),
    ]
